#!/usr/bin/env python

# keywordline = "! PBEh-3c Opt CPCM(Chloroform)"
keywordline = input("Enter keyword line (including exclamation mark): \n")
nprocsline = "\n\n%pal nprocs 16 end\n\n"

with open("crest_conformers.xyz", "r") as infile:
    # read the number of atoms
    natoms = int(infile.readline().strip())
    infile.seek(0) # go back to the start of the file

    conf = 0
    linecounter = 0
    for line in infile:
        linecounter = linecounter + 1 # iterates from 1 to (2+natoms)
        if (1 <= linecounter <= 2): # skip over the natoms + energy lines
            continue
        if (linecounter == 3):
            conf = conf + 1
            outfile_name = "conf{0}.opt.inp".format(conf) # generate the name of the output file
            outfile = open(outfile_name, "a") # preferred over "with open as file" to avoid unnecessary file opening/closing steps
            outfile.write(keywordline)
            outfile.write(nprocsline)
            outfile.write("*xyz 0 1\n")
        if (3 <= linecounter <= 2 + natoms):
            outfile.write(line)
        if (linecounter == 2 + natoms):
            outfile.write("*\n\n")
            outfile.close()
            linecounter = 0

print("Done.")

