#!/usr/bin/env python

import glob
infiles = glob.glob("*.opt.xyz")

# keywordline = "! PBEh-3c Opt CPCM(Chloroform)"
#print "(opt2sp) Enter keyword line (including exclamation mark): \n >>", # trailing comma removes newline from print
keywordline = input("(opt2sp) Enter keyword line (including exclamation mark): \n >>")
nprocsline = "\n\n%pal nprocs 16 end\n\n"

# determine number of atoms
with open(infiles[0], "r") as testfile:
    natoms = int(testfile.readline().strip())

for infile_name in infiles:
    linecounter = 0
    outfile_name = infile_name.replace(".opt.xyz", ".sp.inp")
    outfile = open(outfile_name, "a")
    outfile.write(keywordline)
    outfile.write(nprocsline)
    outfile.write("*xyz 0 1\n")

    with open(infile_name, "r") as infile:
        for line in infile:
            linecounter = linecounter + 1
            if (1 <= linecounter <= 2):
                continue;
            else:
                outfile.write(line)

    outfile.write("*\n\n")
    outfile.close()

print("Done.")
